/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6c522b02-457b-4d3b-bcd4-f3f573dff255",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CHpdsqM46",
    "aws_user_pools_web_client_id": "5dbk02t0ih2gim35b1g22oek7v",
    "oauth": {
        "domain": "debugwithshuo-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3001/",
        "redirectSignOut": "http://localhost:3001/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_user_files_s3_bucket": "amplifytutc2c42b0eed8d49a480473a733087e475224506-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
